---
title: "graphs for presentation"
output: html_document
---

```{r setup, include=FALSE}
#options(htmltools.dir.version = FALSE)
# see: https://github.com/yihui/xaringan
# install.packages("xaringan")
# see: 
# https://github.com/yihui/xaringan/wiki
# https://github.com/gnab/remark/wiki/Markdown
options(width=110)
options(digits = 4)
library("tidyr")
library("dplyr")
library("tibble")
library("rlang")
library("reshape2")
library("ggplot2")
library("parallel")
library("MPTinR")
library("TreeBUGS")
library("runjags")
library("purrr")
library("readr")
library("broom") # for tidy
source("../../scripts/auxiliary_functions.R")
source("../../scripts/summary_plots.R")
load("../../broeder_exp1/model_orig.eqn-exp1.txt.RData")
results1 <- results

load("../../broeder_exp1/model_orig_qrest.eqn-exp1.txt.RData")
results2 <- results

load("../../broeder_exp1/model_orig_rrest.eqn-exp1.txt.RData")
results3 <- results
```

gof

```{r, echo = FALSE, warning=FALSE, fig.width=9.5, fig.height=6}
gof <- bind_rows(unnest(results1, gof),
                 unnest(results2, gof),
                 unnest(results3, gof)
)

gof$pooling <- ifelse(gof$pooling=="no",
                       'No',
                       ifelse(gof$pooling=="complete",
                              'Comp',
                              'PP'))
gof$package <- ifelse(gof$package=="MPTinR",
                       'MR',
                       'TB')

gof$method <- ifelse(gof$method=="PB/MLE",
                      'PB',
                      ifelse(gof$method=="asymptotic",
                             'asy',
                             ifelse(gof$method=="simple",
                                    '',
                                    ifelse(gof$method=="trait",
                                           'trait',
                                           ifelse(gof$method=="trait_uncorrelated",
                                                  'trait_u',
                                                  'beta')))))
gof$focus <- ifelse(gof$focus=="mean",
                      'Mean',
                      ifelse(gof$focus=="cov",
                             'Covariance',
                             gof$focus))

gof$model <- ifelse(gof$model=='model_orig.eqn',
                     'Original Model',
                     ifelse(gof$model=='model_orig_qrest.eqn',
                            'Q Restricted',
                            'R Restricted'))

ggplot(gof, aes(y = p, 
             x = interaction(method, pooling, package), col=model)) + 
  geom_point(size=2) + ylim(0, 1) + 
  geom_hline(yintercept = .05, lty = 2)+
  theme_bw() + coord_flip() +
  facet_wrap(~focus) +
  labs(x='Analysis approach',y='p value', color='Model', title='Goodness of fit')+
  theme(plot.title=element_text(face = 'bold',size=12, hjust = 0.5))

```

gof per condition


```{r, echo = FALSE, warning=FALSE, fig.width=9.5, fig.height=10}
gof_group <- bind_rows(unnest(results1, gof_group),
                 unnest(results2, gof_group),
                 unnest(results3, gof_group)
)

gof_group$pooling <- ifelse(gof_group$pooling=="no",
                       'No',
                       ifelse(gof_group$pooling=="complete",
                              'Comp',
                              'PP'))
gof_group$package <- ifelse(gof_group$package=="MPTinR",
                       'MR',
                       'TB')

gof_group$method <- ifelse(gof_group$method=="PB/MLE",
                      'PB',
                      ifelse(gof_group$method=="asymptotic",
                             'asy',
                             ifelse(gof_group$method=="simple",
                                    '',
                                    ifelse(gof_group$method=="trait",
                                           'trait',
                                           ifelse(gof_group$method=="trait_uncorrelated",
                                                  'trait_u',
                                                  'beta')))))
gof_group$focus <- ifelse(gof_group$focus=="mean",
                      'Mean',
                      ifelse(gof_group$focus=="cov",
                             'Covariance',
                             gof_group$focus))

gof_group$model <- ifelse(gof_group$model=='model_orig.eqn',
                     'Original Model',
                     ifelse(gof_group$model=='model_orig_qrest.eqn',
                            'Q Restricted',
                            'R Restricted'))

                          
gof_group$condition <- ifelse(gof_group$condition=="strong_naming",
                         'Strong wording',
                         'Weak wording'
)

ggplot(gof_group, aes(y = p, 
             x = interaction(method, pooling, package), 
             col = model)) + 
  geom_point(size=2) + ylim(0, 1) + 
  geom_hline(yintercept = .05, lty = 2)+
  facet_grid(condition ~ focus) +
  theme_bw() +
  coord_flip() +
  labs(x='Analysis approach', y='p value', color='Model', title='Goodness of fit per condition')+
  theme(plot.title=element_text(face = 'bold',size=12, hjust = 0.5))
```

core parameters colors=restrictions

```{r, echo = FALSE, warning=FALSE, fig.width=9.5, fig.height=10}
pars <- bind_rows(
  unnest(results1, est_group),
  unnest(results2, est_group),
  unnest(results3, est_group)
)

pars$condition <- ifelse(pars$condition=="strong_naming",
                         'Strong wording',
                         'Weak wording'
)
pars$pooling <- ifelse(pars$pooling=="no",
                       'No',
                       ifelse(pars$pooling=="complete",
                              'Comp',
                              'PP'))
pars$package <- ifelse(pars$package=="MPTinR",
                       'MR',
                       'TB')

pars$method <- ifelse(pars$method=="PB/MLE",
                      'PB',
                      ifelse(pars$method=="asymptotic",
                             'asy',
                             ifelse(pars$method=="simple",
                                    '',
                                    ifelse(pars$method=="trait",
                                           'trait',
                                           ifelse(pars$method=="trait_uncorrelated",
                                                  'trait_u',
                                                  'beta')))))

pars$model <- ifelse(pars$model=='model_orig.eqn',
                     'Original Model',
                     ifelse(pars$model=='model_orig_qrest.eqn',
                            'Q Restricted',
                            'R Restricted'))

shapes <- c(16, 18, 15, 1, 0, 8, 11, 12)
dd <- position_dodge(w = .75)

core <- filter(pars, parameter %in% c("Do", "Dn", "g"))
ggplot(core, aes(y = est, x = interaction(method, pooling,package),
                 shape=model, color=model)) +
  facet_grid(condition ~parameter) +
  geom_errorbar(aes(ymin = est-se, ymax = est+se), position = dd, 
                width = 0.4)+
  geom_point(position = dd, size = 2) + 
  ylim(0,1) + 
  labs(x='Analysis approach',y='Estimate', color='Model',shape='Model', title='Estimates of Core Parameters Across Models')+
  scale_shape_manual(values=shapes) +
  theme_bw() + 
  theme(plot.title=element_text(face = 'bold',size=12, hjust = 0.5))+
  coord_flip()
```

core parameters colors=estimation method

```{r, echo = FALSE, warning=FALSE, fig.width=9.5, fig.height=10}
core <- filter(pars, parameter %in% c("Do", "Dn", "g"))
ggplot(core, aes(y = est, x = model,
                 col=interaction(method, pooling,package),
                 shape=interaction(method, pooling,package))) +
  facet_grid(condition ~parameter) +
  geom_errorbar(aes(ymin = est-se, ymax = est+se), position = dd, 
                width = 0.4)+
  geom_point(position = dd, size = 2) + 
  ylim(0,1) + 
  labs(x='Model',y='Estimate', color='Analysis approach',shape='Analysis approach', title='Estimates of Core Parameters Across Models')+
  scale_shape_manual(values=shapes) +
  theme_bw() + 
  theme(plot.title=element_text(face = 'bold',size=12, hjust = 0.5))+
  coord_flip()
```

est diff for core 


```{r, echo = FALSE, warning=FALSE, fig.width=9.5, fig.height=8}
res_between <- bind_rows(
  unnest(results1, test_between),
  unnest(results2, test_between),
  unnest(results3, test_between)
)

res_between$condition1 <- 'Strong wording'
res_between$condition2 <- 'Weak wording'

res_between$pooling <- ifelse(res_between$pooling=="no",
                       'No',
                       ifelse(res_between$pooling=="complete",
                              'Comp',
                              'PP'))
res_between$package <- ifelse(res_between$package=="MPTinR",
                       'MR',
                       'TB')

res_between$method <- ifelse(res_between$method=="PB/MLE",
                      'PB',
                      ifelse(res_between$method=="asymptotic",
                             'as',
                             ifelse(res_between$method=="simple",
                                    '',
                                    ifelse(res_between$method=="trait",
                                           'trait',
                                           ifelse(res_between$method=="trait_uncorrelated",
                                                  'trait_u',
                                                  res_between$method)))))
res_between$model <- ifelse(res_between$model=='model_orig.eqn',
                     'Original Model',
                     ifelse(res_between$model=='model_orig_qrest.eqn',
                            'Q Restricted',
                            'R Restricted'))
dd <- position_dodge(w = .75)
core2 <- filter(res_between, parameter %in% c("Do", "Dn", "g"))
ggplot(core2, aes(y = est_diff, x = model,
                  col=interaction(method, pooling,package),
                  shape=interaction(method, pooling,package))) +
  facet_wrap(~parameter, ncol=3)+
  geom_errorbar(aes(ymin = ci_0.025, ymax = ci_0.975), 
                position = dd, width = 0.5)+
  geom_point(position = dd, size=2) + ylim(-1,1) + 
  labs(x='Model',y='Estimated Difference', color='Analysis approach',shape='Analysis approach', title='Parameter Differences Between Conditions Across Models: Core Parameters')+
  scale_shape_manual(values=shapes) +
  theme_bw() + geom_hline(yintercept = 0, lty = 2) +
  theme(plot.title=element_text(face = 'bold',size=12, hjust = 0.5))+
  coord_flip()
```

q parameters

```{r, echo = FALSE, warning=FALSE, message=FALSE, fig.width=9.5, fig.height=8}

params_q <- filter(pars, parameter %in% c("q_1", "q_2", "q_3", "q_6", "q_7", "q_8"))
ggplot(params_q, aes(y = est, x = interaction(method, pooling,package),
                 shape=model, color=model)) +
  facet_grid(condition ~parameter) +
  geom_errorbar(aes(ymin = est-se, ymax = est+se), position = dd, 
                width = 0.4)+
  geom_point(position = dd, size = 2) + 
  scale_shape_manual(values=shapes) +
  scale_y_continuous(breaks=seq(0,1,by=.5),limits=c(0,1))+ 
  labs(x='Analysis approach', y='Estimate', color='Model',shape='Model', title='Estimates of Q Parameters Across Models')+
  theme_bw() + 
  theme(plot.title=element_text(face = 'bold',size=12, hjust = 0.5))+
  coord_flip()
```

est diff

```{r, echo = FALSE, warning=FALSE, fig.width=9.5, fig.height=8}
params_q <- filter(res_between, parameter %in% c("q_1", "q_2", "q_3", "q_6", "q_7", "q_8"))
ggplot(params_q, aes(y = est_diff, x = model,
                     col=interaction(method, pooling,package),
                     shape=interaction(method, pooling,package))) +
  facet_wrap(~parameter, ncol=6)+
  geom_errorbar(aes(ymin = ci_0.025, ymax = ci_0.975), 
                position = dd, width = 0.5)+
  geom_point(position = dd, size=2) +  
  scale_y_continuous(breaks=seq(-1,1,by=1),limits=c(-1,1))+ 
  labs(x='Model',y='Estimated Difference', color='Analysis approach',shape='Analysis approach', title='Parameter Differences Between Conditions Across Models: Q Parameters')+
  scale_shape_manual(values=shapes) +
  theme_bw() + geom_hline(yintercept = 0, lty = 3) +
  theme(plot.title=element_text(face = 'bold',size=12, hjust = 0.5))+
  coord_flip()
```

r parameters

```{r, echo = FALSE, warning=FALSE, message=FALSE, fig.width=9.5, fig.height=8}

params_r <- filter(pars, parameter %in% c("r_1", "r_2", "r_3", "r_6", "r_7", "r_8"))
ggplot(params_r, aes(y = est, x = interaction(method, pooling,package),
                 shape=model, color=model)) +
  facet_grid(condition ~parameter) +
  geom_errorbar(aes(ymin = est-se, ymax = est+se), position = dd, 
                width = 0.4)+
  geom_point(position = dd, size = 2) + 
  scale_shape_manual(values=shapes) +
  scale_y_continuous(breaks=seq(0,1,by=.5),limits=c(0,1))+ 
  labs(x='Analysis approach', y='Estimate', color='Model',shape='Model', title='Estimates of R Parameters Across Models')+
  theme_bw() + 
  theme(plot.title=element_text(face = 'bold',size=12, hjust = 0.5))+
  coord_flip()
```

est diff for r par

```{r, echo = FALSE, warning=FALSE, fig.width=9.5, fig.height=8}
params_r <- filter(res_between, parameter %in% c("r_1", "r_2", "r_3", "r_6", "r_7", "r_8"))
ggplot(params_r, aes(y = est_diff, x = model,
                     col=interaction(method, pooling,package),
                     shape=interaction(method, pooling,package))) +
  facet_wrap(~parameter, ncol=6)+
  geom_errorbar(aes(ymin = ci_0.025, ymax = ci_0.975), 
                position = dd, width = 0.5)+
  geom_point(position = dd, size=2) + 
  scale_y_continuous(breaks=seq(-1,1,by=1),limits=c(-1,1))+ 
  labs(x='Model',y='Estimated Difference', color='Analysis approach',shape='Analysis approach', title='Parameter Differences Between Conditions Across Models: R Parameters')+
  scale_shape_manual(values=shapes) +
  theme_bw() + geom_hline(yintercept = 0, lty = 3) +
  theme(plot.title=element_text(face = 'bold',size=12, hjust = 0.5))+
  coord_flip()
```
