---
title: "A Multiverse Pipeline for MPT models "
subtitle: "Applications to Recognition Memory"
author: "Henrik Singmann (Twitter: <a href='https://twitter.com/HenrikSingmann'>@HenrikSingmann</a>)<br/>Georgia Eleni Kapetaniou (kapetaniou.el@gmail.com)<br/>University of Zurich<br/>https://github.com/singmann/mptmultiverse-2htm"
date: "April 2018"
output:
  xaringan::moon_reader:
    css: ["default", "default-fonts", "my-theme.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'

---

class: small, center


| Data set        |Sample          | Mean No of Trials  |
| -------------|:-------------:| -----:|
| Dube_2012-P        | 27  | 400 |
| Dube_2012-W       |  22      |   400 |
|Heathcote_2006_e1  | 16     |    560 |
|Heathcote_2006_e2 | 23 | 560|
|Jaeger_2012|63|120|
|Jang_2009|33|140|
|Koen_2010_pure |32|320|
|Koen_2011|20|600|
|Koen-2013_full|48|200|
| Koen-2013_immediate |48|300|
|Pratte_2010 |97|480|
| Smith_2004|30|140|

--- 


---

class: small, center


| Data set        |Sample          | Mean No of Trials  |
| -------------|:-------------:| -----:|
|Dube & Rotello (2012, Exp. 1, Pictures (P))| 27  | 400 |
|Dube & Rotello (2012, Exp. 1, Words (W))|  22      |   400 |
|Heathcote et al. (2006, Exp. 1)  | 16     |    560 |
|Heathcote et al. (2006, Exp. 2) | 23 | 560|
|Jaeger et al. (2012, Exp. 1, no cue)|63|120|
|Jang et al. (2009)|33|140|
|Koen & Yonelinas (2010, pure study)|32|320|
|Koen & Yonelinas (2011)|20|600|
|Koen et al. (2013, Exp. 2, full attention)|48|200|
|Koen et al. (2013, Exp. 4, immediate test)|48|300|
|Pratte et al. (2010)|97|480|
|Smith & Duncan (2004, Exp. 2)|30|140|

---

class: small

### References 
- Bröder, A., Kellen, D., Schütz, J., & Rohrmeier, C. (2013). Validating a two-high-threshold measurement model for confidence rating data in recognition. *Memory*, 21(8), 916-944. https://doi.org/10.1080/09658211.2013.767348
- Dube, C., Starns, J. J., Rotello, C. M., & Ratcliff, R. (2012). Beyond ROC curvature: Strength effects and response time data support continuous-evidence models of recognition memory. *Journal of Memory and Language*, 67(3), 389-406. https://doi.org/10.1016/j.jml.2012.06.002
- Jaeger, A., Cox, J. C., & Dobbins, I. G. (2012). Recognition confidence under violated and confirmed memory expectations. *Journal of Experimental Psychology: General*, 141(2), 282-301. https://doi.org/10.1037/a0025687
- Koen, J. D., Aly, M., Wang, W.-C., & Yonelinas, A. P. (2013). Examining the causes of memory strength variability: Recollection, attention failure, or encoding variability? *Journal of Experimental Psychology: Learning, Memory, and Cognition*, 39(6), 1726-1741. https://doi.org/10.1037/a0033671
- Steegen, S., Tuerlinckx, F., Gelman, A., & Vanpaemel, W. (2016). Increasing Transparency Through a Multiverse Analysis. *Perspectives on Psychological Science*, 11(5), 702-712. https://doi.org/10.1177/1745691616658637
